/**
 * TypeScript declarations from template param schemas (`frontmail types`).
 * Output format matches the server-side generator in `packages/templates` and additionally
 * augments the `FrontmailTemplates` interface of the installed SDK packages.
 */

export type ParamType = 'string' | 'text' | 'email' | 'url' | 'number' | 'boolean' | 'date' | 'enum' | 'html' | 'list';

/** Template parameter definition as returned by `GET /v1/templates`. */
export interface ParamDef {
  name: string;
  label?: string;
  description?: string;
  type: ParamType;
  required: boolean;
  default?: unknown;
  sampleValue?: unknown;
  enumValues?: string[];
  itemFields?: ParamDef[];
  minLength?: number;
  maxLength?: number;
  min?: number;
  max?: number;
  pattern?: string;
}

export interface TemplateSchema {
  templateId: string;
  name: string;
  params: ParamDef[];
}

/** SDK packages that expose an augmentable `FrontmailTemplates` interface. */
export const SDK_MODULES = [
  '@frontmail/browser',
  '@frontmail/react',
  '@frontmail/vue',
  '@frontmail/svelte',
  '@frontmail/react-native',
  '@frontmail/node',
] as const;

export interface GenerateOptions {
  /** Modules whose `FrontmailTemplates` interface is augmented. Default: all SDK modules. */
  modules?: readonly string[];
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const propKey = (name: string) => (IDENT.test(name) ? name : JSON.stringify(name));
const comment = (text: string) => text.replace(/\*\//g, '* /').replace(/\s+/g, ' ').trim();

export function pascalCase(name: string): string {
  const words = name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
  let out = words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  if (!out) out = 'Template';
  if (/^\d/.test(out)) out = 'Template' + out;
  return out;
}

function tsType(def: ParamDef, indent: string): string {
  switch (def.type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enum':
      return def.enumValues?.length ? def.enumValues.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    case 'list':
      if (!def.itemFields?.length) return 'Array<string | number | boolean | Record<string, unknown>>';
      return 'Array<' + objectType(def.itemFields, indent) + '>';
    default:
      // string, text, email, url, html, date (ISO 8601 string)
      return 'string';
  }
}

const TYPE_NOTES: Partial<Record<ParamType, string>> = {
  email: 'email address',
  url: 'URL (http/https)',
  date: 'date – ISO 8601 (`YYYY-MM-DD` or full timestamp)',
  html: 'HTML – sanitized before sending',
  text: 'multi-line text',
};

function member(def: ParamDef, indent: string): string {
  const docs = [def.label, def.description, TYPE_NOTES[def.type]]
    .filter((x): x is string => Boolean(x && x.trim()))
    .map(comment);
  if (def.default !== undefined) docs.push('@default ' + comment(JSON.stringify(def.default) ?? ''));
  const optional = !def.required || def.default !== undefined;
  const doc = docs.length ? `${indent}/** ${docs.join(' – ')} */\n` : '';
  return `${doc}${indent}${propKey(def.name)}${optional ? '?' : ''}: ${tsType(def, indent)};`;
}

function objectType(defs: ParamDef[], indent: string): string {
  const inner = indent + '  ';
  return `{\n${defs.map((d) => member(d, inner)).join('\n')}\n${indent}}`;
}

/** Generates `<Name>Params` interfaces and `FrontmailTemplates` augmentations. */
export function generateTypes(templates: TemplateSchema[], options: GenerateOptions = {}): string {
  const modules = options.modules ?? SDK_MODULES;
  const used = new Map<string, number>();
  const names = templates.map((tpl) => {
    const base = pascalCase(tpl.name) + 'Params';
    const n = (used.get(base) ?? 0) + 1;
    used.set(base, n);
    return n === 1 ? base : base.replace(/Params$/, n + 'Params');
  });
  const entries = templates.map((tpl, i) => `${JSON.stringify(tpl.templateId)}: ${names[i]};`);
  const lines = ['// Generated by `frontmail types`. Do not edit by hand – re-run the command instead.', '/* eslint-disable */', ''];
  templates.forEach((tpl, i) => {
    lines.push(`/** ${comment(tpl.name)} (${comment(tpl.templateId)}) */`);
    lines.push(tpl.params.length ? `export interface ${names[i]} ${objectType(tpl.params, '')}` : `export interface ${names[i]} {}`);
    lines.push('');
  });
  lines.push('/** Template id → params. */', 'export interface FrontmailTemplates {');
  entries.forEach((e) => lines.push('  ' + e));
  lines.push('}', '', 'export type FrontmailTemplateId = keyof FrontmailTemplates;', '');
  for (const mod of modules) {
    lines.push(`declare module ${JSON.stringify(mod)} {`, '  interface FrontmailTemplates {');
    entries.forEach((e) => lines.push('    ' + e));
    lines.push('  }', '}', '');
  }
  return lines.join('\n');
}
