// Writes src/version.ts from package.json (svelte-package does not bundle JSON imports).
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
writeFileSync(
  new URL('../src/version.ts', import.meta.url),
  `// Generated by scripts/version.mjs – do not edit.\nexport const VERSION = '${version}';\n`,
);
